### ISSUE TITLE
Error with running the model on the provided data

### ISSUE THREAD

**Issue by loganminhdang** [cchen22/TIGER#1]
Hey, thanks for creating this package.

Understand that this is a highly experimental tool and bugs are to be expected. I tried replicating your code (using your data) but was given the following error: 

Unrecoverable error evaluating the log probability at the initial value. 
Exception: to_matrix(matrix): rows * columns (398720) and vector size (398496) must match in size (in 'C:/Users/ADMIN/AppData/Local/Temp/RtmpA1tsWr/model-7cc63982bb9.stan', line 65, column 2 to column 37) 
Chain 1 Exception: to_matrix(matrix): rows * columns (398720) and vector size (398496) must match in size (in 'C:/Users/ADMIN/AppData/Local/Temp/RtmpA1tsWr/model-7cc63982bb9.stan', line 65, column 2 to column 37)
Warning: Fitting finished unexpectedly! Use the $output() method for more information.

Error: Fitting failed. Unable to retrieve the draws.

The same error occurred when I ran the model on both my own data and other databases of Dorothea. Can you please advise?

**Comment by cchen22** [comment]
Hey @loganminhdang 
Thanks for your interest in TIGER!

Hmm, this error is strange. It looks like the product of the number of transcription factors and target genes doesn't match the size of elements in the regulatory network. I can't reproduce this error using my test data "TIGER::expr" and "TIGER::prior". Could you provide your R code and the full output in R for me to take a look?

Thanks,
Chen
